path: /org  
url:  'http://dmitriikonstantin.github.io/org'
theme: jekyll-theme-minimal

#markdown: kramdown

#sass:
# sass_dir: css
# style:    expanded

permalink: /:title

include: ["_pages"]
exclude:
- README.md

excerpt_separator: ""

safe: true
lsi: false
